# Generated by Django 3.0.3 on 2020-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/Story/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/Story/')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/cScience/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/cScience/'),
        ),
    ]
