# Generated by Django 3.0.3 on 2020-03-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_auto_20200321_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/Story/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/Story/')),
            ],
        ),
    ]
