# Generated by Django 3.0.3 on 2020-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_bookpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpersonal',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/PersonalBook/'),
        ),
        migrations.AlterField(
            model_name='bookpersonal',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/PersonalBook/'),
        ),
    ]
