# Generated by Django 3.0.3 on 2020-05-31 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mesaj', '0002_auto_20200531_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Kullanıcı Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alıcı', to=settings.AUTH_USER_MODEL),
        ),
    ]
