# Generated by Django 3.0.3 on 2020-04-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='Öğrenci Adı')),
            ],
        ),
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Kullanıcı Adı:')),
                ('class_teacher_name', models.CharField(max_length=20, verbose_name='Sınıf Öğretmeni')),
            ],
        ),
        migrations.CreateModel(
            name='ClassHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(auto_now_add=True, null=True)),
                ('class_code', models.CharField(max_length=6)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.NewClass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.ClassContent')),
            ],
        ),
    ]
