# Generated by Django 3.0.3 on 2020-04-27 04:43

import classRoom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classhomework',
            name='class_code',
        ),
        migrations.AddField(
            model_name='classhomework',
            name='files',
            field=models.FileField(null=True, upload_to='HomeWorks/'),
        ),
        migrations.AddField(
            model_name='newclass',
            name='class_code',
            field=models.CharField(default=classRoom.models.id_generator, max_length=6),
        ),
        migrations.AlterField(
            model_name='newclass',
            name='class_name',
            field=models.CharField(max_length=20, verbose_name='Sınıf Adı:'),
        ),
    ]
