# Generated by Django 3.0.3 on 2020-04-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classRoom', '0002_auto_20200427_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='classhomework',
            name='is_deliver',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci Adı'),
        ),
        migrations.AlterField(
            model_name='newclass',
            name='class_teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sınıf Öğretmeni'),
        ),
    ]
