# Generated by Django 3.0.3 on 2020-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0003_auto_20200429_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='student_name',
            field=models.CharField(max_length=50, verbose_name='Öğrenci Adı'),
        ),
    ]
