# Generated by Django 3.0.3 on 2020-04-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0004_auto_20200429_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhomework',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.NewClass'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.ClassContent'),
        ),
    ]
