# Generated by Django 3.0.3 on 2020-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0005_auto_20200429_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclass',
            name='class_teacher_name',
            field=models.CharField(max_length=20, verbose_name='auth.User'),
        ),
    ]
