# Generated by Django 3.0.3 on 2020-05-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0009_auto_20200506_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classRoom.NewClass'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classRoom.NewClass'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classRoom.ClassContent'),
        ),
    ]
