# Generated by Django 3.0.3 on 2020-05-14 10:50

import classRoom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0010_auto_20200513_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='classhomework',
            name='homework_code',
            field=models.CharField(blank=True, default=classRoom.models.id_generator, max_length=6, null=True),
        ),
    ]
