# Generated by Django 3.0.3 on 2020-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0011_classhomework_homework_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classhomework',
            name='homework_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
