# Generated by Django 3.0.3 on 2020-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0012_auto_20200514_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='classhomework',
            name='end_clock',
            field=models.TimeField(null=True, verbose_name='Bitiş Saati(h/m/s)'),
        ),
        migrations.AddField(
            model_name='classhomework',
            name='is_end',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
