# Generated by Django 3.0.3 on 2020-05-15 19:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0013_auto_20200515_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_name',
        ),
        migrations.AddField(
            model_name='homework',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ödev İçeriği'),
        ),
        migrations.AddField(
            model_name='homework',
            name='end_clock',
            field=models.TimeField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Saati(h:m:s)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='end_date',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_end',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ödev İçeriği'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='end_clock',
            field=models.TimeField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Saati(h:m:s)'),
        ),
        migrations.AlterField(
            model_name='classhomework',
            name='end_date',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classRoom.NewClass'),
        ),
    ]
