# Generated by Django 3.0.3 on 2020-05-22 15:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classRoom', '0015_auto_20200516_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontent',
            name='class_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Sınıf Adı:'),
        ),
        migrations.AddField(
            model_name='classhomework',
            name='class_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Sınıf Adı:'),
        ),
        migrations.AddField(
            model_name='classhomework',
            name='student_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Öğrenci Adı:'),
        ),
        migrations.AddField(
            model_name='homework',
            name='submit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teslim Eden Sayısı'),
        ),
        migrations.CreateModel(
            name='ClassPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Post')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('files', models.FileField(blank=True, null=True, upload_to='Classes/Posts/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classRoom.NewClass')),
            ],
        ),
    ]
