# Generated by Django 3.0.3 on 2020-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0016_auto_20200522_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontent',
            name='student_naame',
            field=models.CharField(max_length=20, null=True, verbose_name='Sınıf Adı:'),
        ),
    ]
