# Generated by Django 3.0.3 on 2020-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0017_classcontent_student_naame'),
    ]

    operations = [
        migrations.AddField(
            model_name='classhomework',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
