# Generated by Django 3.0.3 on 2020-05-26 19:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Şirket Adı')),
                ('position', models.CharField(max_length=50, verbose_name='Pozisyon')),
                ('started_date', models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Başlangıç Tarihi(mm/dd/yyyy)')),
                ('end_date', models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('surname', models.CharField(max_length=50, verbose_name='Başlık')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('about', models.CharField(max_length=150, verbose_name='Hakkında')),
                ('photo', models.FileField(blank=True, null=True, upload_to='Photo/')),
                ('high_school', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lise')),
                ('university', models.CharField(blank=True, max_length=50, null=True, verbose_name='Üniversite')),
                ('master_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yüksek Lisans')),
                ('phd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doktora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('article_image', models.FileField(blank=True, null=True, upload_to='HomeWorks/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
