# Generated by Django 3.0.3 on 2020-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200526_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_date_high_school',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date_master_degree',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date_phd',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date_university',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Bitiş Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='started_date_high_school',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Başlangıç Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='started_date_master_degree',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Başlangıç Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='started_date_phd',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Başlangıç Tarihi(mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='started_date_university',
            field=models.DateField(help_text='Lütfen formata uygun giriniz.', null=True, verbose_name='Başlangıç Tarihi(mm/dd/yyyy)'),
        ),
    ]
